FROM mhart/alpine-node:latest

ENV PROJECT_ID ""

ENV ES_HOST ""

ENV NODE_ENV ""

WORKDIR /app

COPY . /app

RUN npm install
RUN npm run bootstrap -- --scope=@arranger/server --include-filtered-dependencies
RUN npm cache clean -f

EXPOSE 5050

CMD cd modules/server && npm run run-prod

