version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      cluster.name: workflow.elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx2048m
      ELASTIC_PASSWORD: '$ES_PASS'
      xpack.security.enabled: 'true'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '10'
    healthcheck:
      test: 'curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s || exit 1'
      interval: 1m30s
      timeout: 50s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    ports:
      - 5601:5601
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '10'
    depends_on:
      - elasticsearch
    environment:
      LOGGING_QUIET: 'true'
      ELASTICSEARCH_USERNAME: '$ES_USER'
      ELASTICSEARCH_PASSWORD: '$ES_PASS'

  arranger-server:
    build:
      context: ./
      target: server
      dockerfile: Dockerfile
    container_name: arranger-server.local
    depends_on:
      - elasticsearch
    ports:
      - 5050:5050
    environment:
      ES_HOST: http://elasticsearch:9200
      ES_USER: '$ES_USER'
      ES_PASS: '$ES_PASS'
    volumes:
      - '${CONFIG_PATH}:/app/modules/server/configs'
