// TODO: reorganize these types into their actual dependency tree

import type {
	chartsProperties,
	configOptionalProperties,
	configRequiredProperties,
	dataFieldProperties,
	downloadProperties,
	facetsProperties,
	networkAggregationProperties,
	setsProperties,
	tableProperties,
} from './constants.js';

export * from './constants.js';

export type AggConfigs = {
	[dataFieldProperties.DISPLAY_NAME]: string;
	[dataFieldProperties.DISPLAY_TYPE]: string;
	[dataFieldProperties.FIELD_NAME]: string;
	[dataFieldProperties.IS_ACTIVE]: boolean; // TODO: what is this? active = API vs show = UI? "isActive"
	[dataFieldProperties.SHOW]: boolean;
	// TODO: implement these
	// can change show
	// max results
	// collapsible
};

export type ChartConfigs = {
	[chartsProperties.QUERY]: string;
};

export type ColumnConfigs = {
	[dataFieldProperties.ACCESSOR]: string;
	[dataFieldProperties.CAN_CHANGE_SHOW]: boolean;
	[dataFieldProperties.DISPLAY_FORMAT]: string;
	[dataFieldProperties.DISPLAY_NAME]: string;
	[dataFieldProperties.DISPLAY_TYPE]: string;
	[dataFieldProperties.DISPLAY_VALUES]: Record<string, any>; // TODO: not "any". used for "readable" replacements e.g. true as "yes"
	[dataFieldProperties.FIELD_NAME]: string;
	[dataFieldProperties.IS_ARRAY]: boolean; // should it be displayed as a list of items, or leave as a single string
	[dataFieldProperties.JSON_PATH]: string;
	[dataFieldProperties.QUERY]: string;
	[dataFieldProperties.SHOW]: boolean;
	[dataFieldProperties.SORTABLE]: boolean;
};

export type DownloadsConfigs = {
	[downloadProperties.ALLOW_CUSTOM_MAX_DOWNLOAD_ROWS]?: boolean;
	[downloadProperties.DOWNLOAD_STREAM_BUFFER_SIZE]?: number;
	[downloadProperties.MAX_DOWNLOAD_ROWS]?: number;
};

// TODO: make this a union of types
export type DisplayType = 'all' | 'bits' | 'boolean' | 'bytes' | 'date' | 'list' | 'nested' | 'number';

export type ExtendedConfigs = {
	[dataFieldProperties.DISPLAY_NAME]: string;
	[dataFieldProperties.DISPLAY_TYPE]: string;
	[dataFieldProperties.DISPLAY_VALUES]: Record<string, any>; // TODO: not "any"
	[dataFieldProperties.FIELD_NAME]: string;
	[dataFieldProperties.IS_ACTIVE]: boolean; // TODO: what is this?
	[dataFieldProperties.IS_ARRAY]: boolean;
	[dataFieldProperties.PRIMARY_KEY]: boolean;
	[dataFieldProperties.QUICKSEARCH_ENABLED]: boolean;
	[dataFieldProperties.RANGE_STEP]: number;
	[dataFieldProperties.TYPE]: DisplayType;
	[dataFieldProperties.UNIT]: string;
};

export type FacetsConfigs = {
	[facetsProperties.AGGS]: AggConfigs[];
};

export type MatchBoxConfigs = {
	[dataFieldProperties.DISPLAY_NAME]: string;
	[dataFieldProperties.FIELD_NAME]: string;
};

export type SetsConfigs = {
	[setsProperties.INDEX]: string;
	[setsProperties.TYPE]: string;
};

export type SortingConfigs = {
	[tableProperties.DESCENDING]: boolean;
	[dataFieldProperties.FIELD_NAME]: string;
	[dataFieldProperties.IS_ACTIVE]: boolean;
};

export type TableConfigs = {
	[tableProperties.COLUMNS]: ColumnConfigs[];
	[tableProperties.DEFAULT_SORTING]?: SortingConfigs[];
	[tableProperties.MAX_RESULTS_WINDOW]?: number;
	[tableProperties.ROW_ID_FIELD_NAME]?: string;
};

export type NetworkAggregation = {
	[networkAggregationProperties.DISPLAY_NAME]: string;
	[networkAggregationProperties.DOCUMENT_TYPE]: string;
	[networkAggregationProperties.GRAPHQL_URL]: string;
};

export type ConfigsObject = {
	// Arranger will fail without these
	[configRequiredProperties.DOCUMENT_TYPE]: string;
	[configRequiredProperties.ES_HOST]: string;
	[configRequiredProperties.ES_PASS]: string;
	[configRequiredProperties.ES_USER]: string;
	[configRequiredProperties.INDEX]: string;
} & Partial<{
	[configOptionalProperties.DISABLE_FILTERS]: boolean;
	[configOptionalProperties.DISABLE_GRAPHQL_PLAYGROUND]: boolean;
	[configOptionalProperties.ENABLE_ADMIN]: boolean;
	[configOptionalProperties.ENABLE_DEBUG]: boolean;
	[configOptionalProperties.ENABLE_LOGS]: boolean;
	[configOptionalProperties.ENABLE_NETWORK_AGGREGATION]: boolean;
	[configOptionalProperties.ENABLE_SETS]: boolean;
	// these have defaults or can be autogenerated
	[configOptionalProperties.CHARTS]: ChartConfigs;
	[configOptionalProperties.DOWNLOADS]: DownloadsConfigs;
	[configOptionalProperties.EXTENDED]: ExtendedConfigs[];
	[configOptionalProperties.FACETS]: FacetsConfigs;
	[configOptionalProperties.INSTANCE_ID]: string;
	[configOptionalProperties.MATCHBOX]: MatchBoxConfigs[];
	[configOptionalProperties.SETS]: SetsConfigs;
	[configOptionalProperties.TABLE]: TableConfigs;
	[configOptionalProperties.NETWORK_AGGREGATION]: NetworkAggregation[];
}>;
