/**
 * Function will return SQON to be passed to download stream
 * @param req request that contains sqon generated by arranger filter.
 */
export function arrangerFilterDownload(req) {
  try {
    // add user-selected identifiers

    // return custom sqon
    return req.sqon;
  } catch (error) {
    console.log(`Error returning download SQON: ${error}`);
  }
}
