import { GENERATED_SQON_SCHEMA_VERSION } from './generated.js';

export const DEFAULT_SQON_SCHEMA_VERSION = '0.0.0';

const SQON_SCHEMA_VERSION = GENERATED_SQON_SCHEMA_VERSION ?? DEFAULT_SQON_SCHEMA_VERSION;

export default SQON_SCHEMA_VERSION;
