#!/usr/bin/env node
/**
 * Stamps this package's own package.json version into src/version/generated.ts as a plain string
 * literal, so the shipped bundle never needs to read the filesystem at runtime to know its own
 * version (the previous approach: a top-level `readFileSync` of package.json, which broke any
 * browser bundle importing this package, since it's a Node-only API with no browser equivalent).
 *
 * Run via the `pretest`/`prebuild` npm hooks, never committed (see .gitignore).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(resolve(packageDir, 'package.json'), 'utf8'));
const outPath = resolve(packageDir, 'src/version/generated.ts');

const contents = `// Generated by scripts/generateVersion.mjs. Do not edit; do not commit.
export const GENERATED_SQON_SCHEMA_VERSION = ${JSON.stringify(pkg.version)};
`;

writeFileSync(outPath, contents);
console.log(`wrote ${outPath} (${pkg.version})`);
